env:
    es6: true
    node: true
    browser: true
parser: babel-eslint
extends: 
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures: 
    jsx: true
ignorePatterns:
  - 'packages/**/*.ts'
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  semi:
    - error
    - never
  arrow-spacing:
    - 1
    - before: true
      after: true
  no-console:
    - error
    - { allow: ["error"] }
  object-curly-spacing:
    - warn
    - always
  key-spacing:
    - warn
    - afterColon: true
  react/display-name: 0
  space-infix-ops:
    - warn
  no-empty:
    - 0
  no-useless-catch:
    - 0
  no-unused-vars:
    - error
    - argsIgnorePattern: "_"
  no-trailing-spaces:
    - error