parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 6
    sourceType: 'module'
    ecmaFeatures:
        modules: true
plugins: ['@typescript-eslint']
env: 
    es6: true
    browser: true
rules:
    indent:
        - error
        - 4
    semi:
        - error
        - never
    no-use-before-define:
        - error
        - functions: false
    react/prop-types: 
        - off
    react/jsx-key: 
        - off
    arrow-spacing:
        - warn
        - before: true
          after: true
    no-console:
        - error
        - { allow: ["error"] }
    object-curly-spacing:
        - warn
        - always
    key-spacing:
        - warn
        - afterColon: true
    react/display-name: 
        - off
    space-infix-ops:
        - warn
    